name: Caddy

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - caddy.Containerfile

env:
  CADDY_VERSION: 2.11.3
  CADDY_BUILDER_HASH: sha256:13bf132b50ab5a3abd4d62d4da27a9d8fd98818028746fe85e745d73e3e71f3d
  CADDY_HASH: sha256:87aa104ed6c658991e1b0672be271206b7cd9fec452d1bf3ed9ad6f8ab7a2348

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Code checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            caddy.Containerfile

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: push
        env:
          # ref; https://docs.docker.com/build/ci/github-actions/reproducible-builds/
          SOURCE_DATE_EPOCH: 0
        with:
          context: .
          file: ./caddy.Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:caddy-${{ env.CADDY_VERSION }}
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
            CADDY_BUILDER_HASH=${{ env.CADDY_BUILDER_HASH }}
            CADDY_HASH=${{ env.CADDY_HASH }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:caddy-${{ env.CADDY_VERSION }}
          format: "sarif"
          output: "trivy-results.sarif"
          # exit-code: 1 # fail the workflow if vulnerailities are found

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: "trivy-results.sarif"

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: GHCR retention policy
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: caddy-gateway
          package-type: container
          min-versions-to-keep: 51
