name: CI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.26.3"]
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Code checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go }}

      - name: go mod download
        env:
          CGO_ENABLED: 0
        run: |
          go mod download

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: go test
        env:
          CGO_ENABLED: 0
        run: |
          # This ShellCheck disable is for word-splitting which is something we
          # need to occur for this command to work correctly.
          #
          # shellcheck disable=SC2046
          go test $(go list ./... | grep -v /e2e)

      - name: go test -race
        env:
          CGO_ENABLED: 1
        run: |
          # This ShellCheck disable is for word-splitting which is something we
          # need to occur for this command to work correctly.
          #
          # shellcheck disable=SC2046
          go test -race -covermode atomic -coverprofile=covprofile $(go list ./... | grep -v /e2e)

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
