name: CI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.26.4"]
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Code checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: go mod download
        env:
          CGO_ENABLED: 0
        run: |
          go mod download

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: go test
        env:
          CGO_ENABLED: 0
        run: |
          # This ShellCheck disable is for word-splitting which is something we
          # need to occur for this command to work correctly.
          #
          # shellcheck disable=SC2046
          go test $(go list ./... | grep -v /e2e)

      - name: go test -race
        env:
          CGO_ENABLED: 1
        run: |
          # This ShellCheck disable is for word-splitting which is something we
          # need to occur for this command to work correctly.
          #
          # shellcheck disable=SC2046
          go test -race -covermode atomic -coverprofile=covprofile $(go list ./... | grep -v /e2e)

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
